### ISSUE TITLE
Periodic Notes插件设置了新建笔记的位置，点击创建的笔记还是在根目录下

### ISSUE THREAD

**Issue by barye81** [DevilRoshan/obsidian-lunar-calendar#3]
Periodic Notes插件设置了新建笔记的位置，点击创建的笔记还是在根目录下
上一个版本是可以新建在指定的目录下的，这个版本发现有这个问题

**Comment by barye81** [comment]
设置了模版，新建也没有，打开Periodic Notes插件了

**Comment by DevilRoshan** [comment]
<img width="1136" alt="image" src="https://github.com/user-attachments/assets/b3f0ed7a-0035-4334-99f8-3818b4240c7e">

没有复现你的问题，按照这个配置，可以创建笔记

插件版本如下：

<img width="817" alt="image" src="https://github.com/user-attachments/assets/9e9c942d-67a9-4724-a53b-2e146dd183c5">

效果

<img width="813" alt="image" src="https://github.com/user-attachments/assets/0de688bf-7b6f-4240-bccd-6a4032a09f60">

**Comment by barye81** [comment]
找到问题了，Periodic Notes插件换了旧的版本可以了，多谢
